### ISSUE TITLE
Couldn't run the test aplication

### ISSUE THREAD

**Issue by alpert** [ethanhugg/ikran#68]
Hi.
I follewed the instructions from README. I get the mozilla as [1] and build and webrtc too. Set the environment variables. Build the application with no errors. But when i try to run the test application it gives me something like:
"Enter SIP Server IP Address [10.99.10.75]: 192.168.1.245
Enter Remote Peer IP Address [10.99.10.75]: 192.168.1.20
Enter SIP Server username (phone DN for CUCM) [1000]: 1006
Enter Password (not required for CUCM) [Enter]: ****
Enter device name (only required for CUCM) [emannionsip01]: 

Select Mode, (R) normal register,  (P) P2P Mode   [R]: P
key = 6401f902
there was no preexisting q..
create message q with id=0
key = 6501f902
there was no preexisting q..
create message q with id=8001
key = 6601f902
there was no preexisting q..
create message q with id=10002
key = 6701f902
there was no preexisting q..
create message q with id=18003"

and nothing happens. Same for register mode. I use Ubuntu 11.10. Asteriks as SIP server. What could be the problem?
Best regards.

**Comment by alpert** [comment]
And also when i try the addon (which i built without error), the test page (ikran/content/ikran.html) give an warning as "The Ikran add-on could not be loaded!"

**Comment by ethanhugg** [comment]
Hello,

Ikran uses NSPR logging like firefox so if you haven't already you can put in these two environment variables to send it to a file

export NSPR_LOG_FILE=/Users/ehugg/tmp/nspr.log
export NSPR_LOG_MODULES=ikran:5

The entire SIP conversation should be in there.  It's possible that the test app is working for you and you just need to press 'd' to make it dial out.

Regards.

-EH

-----Original Message-----
From: alpert [mailto:reply@reply.github.com]
Sent: Thu 12/8/2011 4:03 AM
To: Ethan Hugg (ehugg)
Subject: [ikran] Couldn't run the test aplication (#68)

Hi.
I follewed the instructions from README. I get the mozilla as [1] and build and webrtc too. Set the environment variables. Build the application with no errors. But when i try to run the test application it gives me something like:
"Enter SIP Server IP Address [10.99.10.75]: 192.168.1.245
Enter Remote Peer IP Address [10.99.10.75]: 192.168.1.20
Enter SIP Server username (phone DN for CUCM) [1000]: 1006
Enter Password (not required for CUCM) [Enter]: ****
Enter device name (only required for CUCM) [emannionsip01]: 

Select Mode, (R) normal register,  (P) P2P Mode   [R]: P
key = 6401f902
there was no preexisting q..
create message q with id=0
key = 6501f902
there was no preexisting q..
create message q with id=8001
key = 6601f902
there was no preexisting q..
create message q with id=10002
key = 6701f902
there was no preexisting q..
create message q with id=18003"

and nothing happens. Same for register mode. I use Ubuntu 11.10. Asteriks as SIP server. What could be the problem?
Best regards.

---

Reply to this email directly or view it on GitHub:
https://github.com/ethanhugg/ikran/issues/68
